version: "3.9"
    
services:
  gropple:
    build: .
    image: tardisx/gropple:latest
    volumes:
      - ./gropple-config-dir:/config
      - ./downloads:/downloads/
    restart: always
    ports:
      - "6123:6123"
