version: "3.9"

services:
  gropple:
    image: tardisx/gropple:v1.1.4
    volumes:
      - /tmp/gropple-config-dir/:/config
      - /tmp/downloads/:/downloads/
    restart: always
    ports:
      - "6123:6123"
